In [1]:
import pandas as pd

In [8]:
enem = (
    pd.read_csv('dados/dados_enem_tratados.csv', encoding='UTF-8', delimiter=',')
)
enem

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210057943671,2022,26 anos ou mais,M,Casado(a)/Mora com companheiro(a),Preta,Brasileiro(a),Já concluí o Ensino Médio,Concluiu depois de 2013,Não Respondeu,...,B,A,A,A,A,A,A,A,A,A
1,210057516120,2022,26 anos ou mais,M,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),Já concluí o Ensino Médio,Concluiu em 2013 ou antes,Não Respondeu,...,E,E,B,E,B,B,E,B,E,B
2,210057280536,2022,Menor de 26 anos,F,Solteiro(a),Preta,Brasileiro(a),Já concluí o Ensino Médio,Concluiu depois de 2013,Não Respondeu,...,A,A,A,A,A,A,C,A,A,B
3,210055724397,2022,Menor de 26 anos,M,Solteiro(a),Parda,Brasileiro(a),Já concluí o Ensino Médio,Concluiu depois de 2013,Não Respondeu,...,B,A,A,C,A,A,C,B,B,B
4,210055097896,2022,Menor de 26 anos,M,Não informado,Parda,Brasileiro(a),Já concluí o Ensino Médio,Concluiu depois de 2013,Não Respondeu,...,A,A,A,A,A,A,B,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476100,210056389903,2022,Menor de 26 anos,M,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,B,A,B,B,B,A,E,A,A,B
3476101,210057205644,2022,26 anos ou mais,F,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,A,A,A,B,A,A,C,A,B,B
3476102,210056699189,2022,Menor de 26 anos,M,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,B,A,B,C,B,A,E,A,B,B
3476103,210056983033,2022,Menor de 26 anos,M,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Não informado,Privada,...,B,A,B,D,A,A,E,A,B,B
3476104,210056307777,2022,Menor de 26 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,A,A,A,B,A,A,C,A,C,B